travis:
  secure:
    BINSTAR_TOKEN: 0dkshcyGSwuPdpIvLpFKOe//VPMNjsHIDxqwoqLsB3DcLKbmhwnaC+qmnuUfpIP3RS2yvyWzq+Qmp/vR3KYlVg8vNGXyGRYtVxZy3iuqlT2lJEocSeo0BdgICA4YneMZLsvoDngMrxOkorE+oZAQugo/LEVfB/VFRx7VR4BrbZM+33HtR9dB2pXAbQjahCn/krzmWVIXJD88jfLYaVxLkkOvqsiasyZ5NJF9gCyhsPcR38bnPWwFZ4dpWp0ca5NevTxv0eBUuvZwPGFaQpqv2ixl0pcy5H7W6UbVuXqhOki/F3sJChfRUnq0ZUrQncdaTswGSKv7B6Zil7uJY4jfpQ4pavN30Aid50HTfnYUzpkG3TvLGq+KbDunem/RbeMoC757Zyc24c5zl7Q+owiQUixeq7pxoKaSjtPIudqoZ7PCb5ov5/wQgIy0iCYysezJn8u3nX8VVghptEZj9EZoB3DZhBPPhD56yijgbD9HanVZu51X+zqJjoW5FGOch7SlwrOLdYbWVukQgD9I87QXhVVLkfwIwSq2Q2abt1CP86dpEakdwVg0yzI80wA3gYWmnRXJsPFcVT2blG7hvS4g1xmxZYzq36r7rbWf6GahUk0O+myl/XFmFQtBzQVxfjwOe1Hw9gBN/u3OBMbGKF9RJ7Ri5SDT93vuNfahpxGkQcI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
